### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by evjeff**
Fixed typo, added my name as an admin

### CODE REVIEW

**Comment by shea-parkes** [comment]
Although I appreciate your contributions, I will need to confirm with the new Milliman owners of this IP before merging your attribution.  I apologize for the inconvenience.

**Comment by shea-parkes** [comment]
Jeffrey: I've referred your request for public "Ownership" status to current staff in our New York office.  However, I personally find it unlikely we'd be able to list you as an owner of a solution being stored under the Milliman organization on GitHub.  Here are a couple possibilities you could make happen now while this is being discussed:
  - I would be happy to merge a pull request that just fixes the typo (and incorporate a commit from you into this repository).  If you don't want to mess with that I'll circle back to fix the typo in a separate commit.
  - Given the MIT License of this solution, you are free to fork this solution and make your own derivative work.  That derivative solution would be subject to the terms of the MIT license (e.g. it needs to include the Milliman copyright notice).

I do appreciate your contributions.

**Comment by evjeff** [comment]
Hi Shea,

Not a problem on any of this. If the easiest thing to do is just fix the
typo that works for me.  Maggie in NY asked me to review the upcoming
journal publication and double check the repo for things to delete.

The only thing I found was the readme typo.  I asked to be an owner just
because I wrote most of the code originally and am an author on the paper.
It really doesn't matter to me though so don't spend a lot of time on it.

Best regards,

Jeff

**Comment by shea-parkes** [comment]
I went ahead and fixed the typo in another commit.  Thanks for catching it.

**Pull request closed without merging**
